name: Render Quarto & Deploy

on:
  push:
    branches: [main]
    paths:
      - communities.csv
      - communities.qmd
      - .github/workflows/render-quarto.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("reactable", "htmltools"))'

      - name: Render Quarto document
        run: quarto render communities.qmd --output-dir docs

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs/
          git commit -m "Auto-rendered site" || echo "No changes"
          git push
